apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: ghcr.io/nadametwaly/react-app-cicd:405985c8721a7455ffe77c80e343584a9427f849
        ports:
        - containerPort: 80